name: i can't use the support discord
description: sad
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Explain the problem you are trying to solve and what you have tried.
        If applicable, include logs - they are in same folder as the launcher: `log/latest.log` - and screenshots/videos
