// Auto-Generated by ZenithProxy Data Generator
package com.zenith.mc.potion;

import com.zenith.mc.Registry;

public final class PotionRegistry {
    public static final Registry<PotionData> REGISTRY = new Registry<PotionData>(46);

    public static final PotionData WATER = REGISTRY.register(new PotionData(0, "water"));

    public static final PotionData MUNDANE = REGISTRY.register(new PotionData(1, "mundane"));

    public static final PotionData THICK = REGISTRY.register(new PotionData(2, "thick"));

    public static final PotionData AWKWARD = REGISTRY.register(new PotionData(3, "awkward"));

    public static final PotionData NIGHT_VISION = REGISTRY.register(new PotionData(4, "night_vision"));

    public static final PotionData LONG_NIGHT_VISION = REGISTRY.register(new PotionData(5, "long_night_vision"));

    public static final PotionData INVISIBILITY = REGISTRY.register(new PotionData(6, "invisibility"));

    public static final PotionData LONG_INVISIBILITY = REGISTRY.register(new PotionData(7, "long_invisibility"));

    public static final PotionData LEAPING = REGISTRY.register(new PotionData(8, "leaping"));

    public static final PotionData LONG_LEAPING = REGISTRY.register(new PotionData(9, "long_leaping"));

    public static final PotionData STRONG_LEAPING = REGISTRY.register(new PotionData(10, "strong_leaping"));

    public static final PotionData FIRE_RESISTANCE = REGISTRY.register(new PotionData(11, "fire_resistance"));

    public static final PotionData LONG_FIRE_RESISTANCE = REGISTRY.register(new PotionData(12, "long_fire_resistance"));

    public static final PotionData SWIFTNESS = REGISTRY.register(new PotionData(13, "swiftness"));

    public static final PotionData LONG_SWIFTNESS = REGISTRY.register(new PotionData(14, "long_swiftness"));

    public static final PotionData STRONG_SWIFTNESS = REGISTRY.register(new PotionData(15, "strong_swiftness"));

    public static final PotionData SLOWNESS = REGISTRY.register(new PotionData(16, "slowness"));

    public static final PotionData LONG_SLOWNESS = REGISTRY.register(new PotionData(17, "long_slowness"));

    public static final PotionData STRONG_SLOWNESS = REGISTRY.register(new PotionData(18, "strong_slowness"));

    public static final PotionData TURTLE_MASTER = REGISTRY.register(new PotionData(19, "turtle_master"));

    public static final PotionData LONG_TURTLE_MASTER = REGISTRY.register(new PotionData(20, "long_turtle_master"));

    public static final PotionData STRONG_TURTLE_MASTER = REGISTRY.register(new PotionData(21, "strong_turtle_master"));

    public static final PotionData WATER_BREATHING = REGISTRY.register(new PotionData(22, "water_breathing"));

    public static final PotionData LONG_WATER_BREATHING = REGISTRY.register(new PotionData(23, "long_water_breathing"));

    public static final PotionData HEALING = REGISTRY.register(new PotionData(24, "healing"));

    public static final PotionData STRONG_HEALING = REGISTRY.register(new PotionData(25, "strong_healing"));

    public static final PotionData HARMING = REGISTRY.register(new PotionData(26, "harming"));

    public static final PotionData STRONG_HARMING = REGISTRY.register(new PotionData(27, "strong_harming"));

    public static final PotionData POISON = REGISTRY.register(new PotionData(28, "poison"));

    public static final PotionData LONG_POISON = REGISTRY.register(new PotionData(29, "long_poison"));

    public static final PotionData STRONG_POISON = REGISTRY.register(new PotionData(30, "strong_poison"));

    public static final PotionData REGENERATION = REGISTRY.register(new PotionData(31, "regeneration"));

    public static final PotionData LONG_REGENERATION = REGISTRY.register(new PotionData(32, "long_regeneration"));

    public static final PotionData STRONG_REGENERATION = REGISTRY.register(new PotionData(33, "strong_regeneration"));

    public static final PotionData STRENGTH = REGISTRY.register(new PotionData(34, "strength"));

    public static final PotionData LONG_STRENGTH = REGISTRY.register(new PotionData(35, "long_strength"));

    public static final PotionData STRONG_STRENGTH = REGISTRY.register(new PotionData(36, "strong_strength"));

    public static final PotionData WEAKNESS = REGISTRY.register(new PotionData(37, "weakness"));

    public static final PotionData LONG_WEAKNESS = REGISTRY.register(new PotionData(38, "long_weakness"));

    public static final PotionData LUCK = REGISTRY.register(new PotionData(39, "luck"));

    public static final PotionData SLOW_FALLING = REGISTRY.register(new PotionData(40, "slow_falling"));

    public static final PotionData LONG_SLOW_FALLING = REGISTRY.register(new PotionData(41, "long_slow_falling"));

    public static final PotionData WIND_CHARGED = REGISTRY.register(new PotionData(42, "wind_charged"));

    public static final PotionData WEAVING = REGISTRY.register(new PotionData(43, "weaving"));

    public static final PotionData OOZING = REGISTRY.register(new PotionData(44, "oozing"));

    public static final PotionData INFESTED = REGISTRY.register(new PotionData(45, "infested"));
}
